### ISSUE TITLE
Bad behavior on abort of file load

### ISSUE THREAD

**Issue by bgribble** [bgribble/mfp#297]
IF you C-o to open a file, then hit ESC to abort while editing the file name, you can be left with a vestigial empty patch with a weird name and sometimes a traceback on the console. 

```
[ 687.406   main] Patch.register_file: registering type 'aoc23_08_a' from file '/home/grib/devel/mfp/aoc23_08_a.mfp'
[ 687.415   main] [TaskNibbler] launching task
[ 687.501   main] Patch loaded, elapsed time 0:00:00.100448
[ 687.677   main] [TaskNibbler] Exception
[ 687.685   main] Traceback (most recent call last):
[ 687.685   main]   File "/usr/lib/python3.11/asyncio/tasks.py", line 500, in wait_for
[ 687.685   main]     return fut.result()
[ 687.685   main]            ^^^^^^^^^^^^
[ 687.685   main]   File "/usr/lib/python3.11/asyncio/locks.py", line 213, in wait
[ 687.685   main]     await fut
[ 687.685   main] asyncio.exceptions.CancelledError
[ 687.685   main]
[ 687.685   main] The above exception was the direct cause of the following exception:
[ 687.685   main]
[ 687.685   main] Traceback (most recent call last):
[ 687.685   main]   File "/home/grib/devel/mfp/.virtual/lib/python3.11/site-packages/mfp/utils.py", line 295, in _task_launcher
[ 687.685   main]     await self._process_queue()
[ 687.685   main]   File "/home/grib/devel/mfp/.virtual/lib/python3.11/site-packages/mfp/utils.py", line 343, in _process_queue
[ 687.685   main]     await asyncio.wait_for(self.new_work.wait(), 0.26)
[ 687.685   main]   File "/usr/lib/python3.11/asyncio/tasks.py", line 502, in wait_for
[ 687.685   main]     raise exceptions.TimeoutError() from exc
```

**Comment by bgribble** [comment]
Fixed this and related issues with the above commit.
